CC=gcc
CARGS=-Wall -O2

entrada_numerica_bubble: entrada_numerica_bubble.c
	$(CC) $(CARGS) entrada_numerica_bubble.c -o main

entrada_numerica_quick_sort: entrada_numerica_quick_sort.c
	$(CC) $(CARGS) entrada_numerica_quick_sort.c -o main

entrada_textual_quick_sort: entrada_textual_quick_sort.c
	$(CC) $(CARGS) entrada_textual_quick_sort.c -o main

entrada_textual_bubble: entrada_textual_bubble.c
	$(CC) $(CARGS) entrada_textual_bubble.c -o main
